export const Config = {
  REST_SERVER: import.meta.env.VITE_APP_REST_SERVER,
  MSCP_ENDPOINT: import.meta.env.VITE_APP_MSCP_ENDPOINT,
  APPOINTMENT_SERVICE_ENDPOINT: import.meta.env
    .VITE_APP_APPOINTMENT_SERVICE_ENDPOINT,
  MEDICAL_SERVICE_ENDPOINT: import.meta.env.VITE_APP_MEDICAL_SERVICE_ENDPOINT,
  MEDICAL_SERVICE_ENDPOINT_API: import.meta.env
    .VITE_APP_MEDICAL_SERVICE_ENDPOINT_API,
  SUBSCRIPTION_SERVICE_ENDPOINT: import.meta.env
    .VITE_APP_SUBSCRIPTION_SERVICE_ENDPOINT,
  SUBSCRIPTION_SERVICE_ENDPOINT_API: import.meta.env
    .VITE_APP_SUBSCRIPTION_SERVICE_ENDPOINT_API,
  INSURANCE_SERVICE_ENDPOINT: import.meta.env
    .VITE_APP_INSURANCE_SERVICE_ENDPOINT,
  COOKIE_REFRESH_TOKEN: import.meta.env.VITE_APP_AUTH_COOKIE_REFRESH_TOKEN,
  WS_REST_SERVER: import.meta.env.VITE_APP_WS_REST_SERVER,

  AWS_DEFAULT_REGION: import.meta.env.VITE_APP_AWS_DEFAULT_REGION,
  AWS_BUCKET: import.meta.env.VITE_APP_AWS_BUCKET,

  NOVU_APP_IDENTIFIER: import.meta.env.VITE_APP_NOVU_APP_IDENTIFIER,
  NOVU_SUBSCRIBER_ID: import.meta.env.VITE_APP_NOVU_SUBSCRIBER_ID,

  I18N_LOCALE: import.meta.env.VITE_APP_I18N_LOCALE,
  I18N_FALLBACK_LOCALE: import.meta.env.VITE_APP_I18N_FALLBACK_LOCALE,

  LIVE_TIMES_ENABLED: import.meta.env.VITE_APP_LIVE_TIMES_ENABLED,

  CONNECT_WORKER: import.meta.env.VITE_APP_CONNECT_WORKER,

  SENTRY_DSN: import.meta.env.VITE_APP_SENTRY_DSN || '',
  SENTRY_ENVIRONMENT: import.meta.env.VITE_APP_SENTRY_ENVIRONMENT || '',

  CHAT_BASE_URL: import.meta.env.VITE_APP_CHAT_BASE_URL,
  CHAT_WEBSITE_TOKEN: import.meta.env.VITE_APP_CHAT_WEBSITE_TOKEN,

  CURRENT_BRAND: import.meta.env.VITE_APP_CURRENT_BRAND,
  SUPPORTED_LANGUAGES: import.meta.env.VITE_APP_SUPPORTED_LANGUAGES,
  URL_DOWNLOAD_APP: import.meta.env.VITE_APP_URL_DOWNLOAD_APP,
  NAME_DOWNLOAD_APP: import.meta.env.VITE_APP_NAME_DOWNLOAD_APP,

  OPENAI_ENDPOINT: import.meta.env.VITE_APP_OPENAI_ENDPOINT,
  OPENAI_MODEL_NAME: import.meta.env.VITE_APP_OPENAI_MODEL_NAME,
  OPENAI_DEPLOYMENT: import.meta.env.VITE_APP_OPENAI_DEPLOYMENT,
  OPENAI_APIKEY: import.meta.env.VITE_APP_OPENAI_APIKEY,
  OPENAI_API_VERSION: import.meta.env.VITE_APP_OPENAI_API_VERSION,
};
